### ISSUE TITLE
new tag/release

### ISSUE THREAD

**Issue by WebFreak001** [atilaneves/monty#1]
There was one commit since the last tag, which greatly improves error messages / diagnosing the error when trying to use this library and not having clang installed. I think it's worth tagging that as 0.0.2

Additionally the `find` command would previously exit non-zero because of non-readable directories, causing the script to exit without any error output, making it hard to debug what was happening.

**Comment by atilaneves** [comment]
I can tag it, but it's currently broken on Arch Linux due to libclang and/or dpp issues, it's not clear.
